Fix a failing test on Python 3.6.
This commit fixes the following Python 3.6 error when running tests:

    TypeError: expected str, bytes or os.PathLike object, not MagicMock

In Python 3.6, os.path.basename() no longer accepts a mock. We thus need to set
a proper return value of subprocess.check_output() because by default, a mocked
call returns a mock.